# Generated by Django 5.2 on 2025-04-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_item_image_itemimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemimage',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(upload_to='item_images/'),
        ),
    ]
