# Generated by Django 5.2 on 2025-04-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_itemimage_is_main_alter_itemimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='profile_image',
            field=models.ImageField(default='null', upload_to='item_images/'),
            preserve_default=False,
        ),
    ]
